import re
html = open('C:/Users/HP/Desktop/signalsonnn/facial-image-warping/frontend/templates/index.html', 'r', encoding='utf-8').read()
html = re.sub(r'<p class="mt-1 text-\[10px\] leading-relaxed text-slate-400">\s*Local LivePortrait expression edit.*?<\/p>', '', html, flags=re.DOTALL)
html = html.replace('İfade Tipi (Preset)', 'Preset')
html = html.replace('Gülümseme (Smile)', 'Smile')
html = html.replace('Kaş Kaldırma (Eyebrow Raise)', 'Eyebrow Raise')
html = html.replace('Kahkaha (Laugh)', 'Laugh')
html = html.replace('Şaşkınlık (Surprise)', 'Surprise')
html = html.replace('Doğal (Neutral)', 'Neutral')
html = html.replace('Göz Kırpma (Wink)', 'Wink')
html = html.replace('Üzgün (Sad)', 'Sad')
html = html.replace('Kızgın (Angry)', 'Angry')
html = html.replace('Yoğunluk (Intensity)', 'Intensity')
open('C:/Users/HP/Desktop/signalsonnn/facial-image-warping/frontend/templates/index.html', 'w', encoding='utf-8').write(html)
